### ISSUE TITLE
Initial migration failed

### ISSUE THREAD

**Issue by Keref** [dappur/framework#21]
Migration failed on 
`Filed 'last_login' doesn't have a default value` while creating the default admin user.

Made it work by changing in the XXX_init_database.php file:
`$table->timestamp('last_login');`
to
`$table->timestamp('last_login')->nullable();`
or
`$table->timestamp('last_login')->useCurrent();`

**Comment by jeffmthomas** [comment]
I have added this fix to the next major release which will be by the end of the week.

**Comment by jeffmthomas** [comment]
This was fixed in v2.1
