### ISSUE TITLE
500 Error Oauth2 users

### ISSUE THREAD

**Issue by aereknaus** [dappur/framework#29]
Been following this project for a while now - update to OAuth and getting following error

    /opt/sites/dappur-test/vendor/slim/slim/Slim/CallableResolver.php
    Line: 104
    Message: [{},"oauth2Users"] is not resolvable...

Also in the providers all providers are saying even though they are set in the file

Client ID and/or Client Secret not found. Facebook might not work until these are added to the settings.json file.

Thanks and keep up the work :)

**Comment by edwardteach42** [comment]
I have not created the oauth2users method/page yet. I think I accidentally skipped it over completely. 

I'm currently making a BUNCH of formatting fixes in preparation for CI. I will address this and should be releasing a new version for you to try within a few days.

**Comment by edwardteach42** [comment]
I have completed the next release and pushed it to the master brand. It mostly includes code simplification and cleanup. I am just finishing writing the notes and will release it as v2.3 later today.

**Comment by edwardteach42** [comment]
Please let me know if you have any issues from the current master branch. I'm closing this issue as it should be resolved in the 2.3 release.
