### ISSUE TITLE
Using SQLite database

### ISSUE THREAD

**Issue by LeftPinkie** [dappur/framework#55]
Can I use SQLite as my database backend instead of MySQL?

**Comment by LeftPinkie** [comment]
I was able to get the migration to work by updating the following:

**./phinx.php:**

    ...
    /*
    foreach ( $dbconf as $key => $value ) {
    $output['environments'][$key] = [
            'adapter' => $value['driver'],
            'host' => $value['host'],
            'name' => $value['database'],
            'user' => $value['username'],
            'pass' => $value['password'],
            'port' => $value['port'],
            'charset'   => $value['charset'],
            'collation' => $value['collation'],
            'prefix' => $value['prefix'],
            'timezone' => $value['timezone']
        ] ;
    }
    */
    $output['environments']['development'] = [
    	'adapter'	=> 'sqlite' ,
    	'name'		=> './data/database.main.sqlite3' ,
    ] ;
    ...

**./app/src/Migration/Migration.php:**

    ...
    $this->capsule->addConnection([
       'driver'    => 'sqlite', //'mysql',
    // 'host'      => $dbconf['host'],
    // 'port'      => $dbconf['port'],
       'database'  => './data/database.main.sqlite3' //$dbconf['database'],
    // 'username'  => $dbconf['username'],
    // 'password'  => $dbconf['password'],
    // 'charset'   => 'utf8',
    // 'collation' => 'utf8_unicode_ci',
    // 'timezone' => $dbconf['timezone']
    ]);
    ...

These are just for the migration.  I think there are other configuration settings.

**Comment by edwardteach42** [comment]
You would also need to update `[./settings.json](https://github.com/dappur/framework/blob/master/settings.json.dist)` to get it to work with the framework.  This has not been tested yet.

**Comment by edwardteach42** [comment]
Tested with SQLite and it worked so I am closing this issue.
