### ISSUE TITLE
ANNOUNCEMENT: v4.0 Coming Soon

### ISSUE THREAD

**Issue by edwardteach42** [dappur/framework#56]
I have been busy with several other projects recently and havent had much time to devote to this.  I am in the process of finishing up a v4.0 release which  cleans up some dappurware as well as some bug fixes.  If you have any requests for other features before I finish this up, now is the time to do so!

**Comment by kak2z7702** [comment]
Hello)) thanks for good job) 
When is the release of version 4 planned?

**Comment by edwardteach42** [comment]
It will be by the end of this weekend for sure.  You can check out the v4.x branch for a preview.  I am just running through and testing everything one last time.  I got sidetracked 3D printing and building a drone.

**Comment by edwardteach42** [comment]
The version 4.0.0 Release Candidate 1 is now out.  I am going to do some testing on this to ensure that it works and will push a final release by the end of the week.
