### ISSUE TITLE
Too long text in page content causes 500 error 

### ISSUE THREAD

**Issue by PoltixeTheDerg** [dappur/framework#59]
As the title says, putting too much text in the "page content" section causes the admin panel to 500 error out and page text not being set

The error put out is this
```
/vagrant/vendor/illuminate/database/Connection.php

Line: 664

Message: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'content' at row 1 (SQL: update `routes` set `content` =`some really long text`, `updated_at` = 2019-07-10 12:17:17 where `id` = 1)
```
I managed to fix this problem by setting the column `content` in the `routes` table to `LONGTEXT` instead of `TEXT`

**Comment by edwardteach42** [comment]
The page content for custom pages has been set to LONGTEXT and is part of the v4.0.0-RC1 release
